### ISSUE TITLE
"session" is not allowed

### ISSUE THREAD

**Issue by lemonizer** [hapijs/bassmaster#71]
Recently just updated our application to hapi 14.2.0 and started noticing that our batch endpoint stopped working with the following error:

```
1] "session" is not allowed
    at Object.exports.Err.exports.process (/api/node_modules/joi/lib/errors.js:154:19)
    at _validateWithOptions (/api/node_modules/joi/lib/any.js:601:31)
    at root.validate (/api/node_modules/joi/lib/index.js:105:23)
    at root.attempt (/api/node_modules/joi/lib/index.js:134:29)
    at root.assert (/api/node_modules/joi/lib/index.js:129:14)
    at Object.exports.inject (/api/node_modules/hapi/node_modules/shot/lib/index.js:51:13)
...
```

Seems like as of Shot 3.2.1, the inject options are now validated against a Joi schema which does not have the `session` attribute: [issue #71](https://github.com/hapijs/shot/pull/71). 

Shot 3.3.1 added an option to disable the validation that fixes the issue above: [Issue #75](https://github.com/hapijs/shot/issues/75)

That being said, I can't seem to find that particular property being used anywhere else in Bassmaster nor did I find any references to it in Shot.

**Comment by pwarnock** [comment]
I encountered the same error. I reverted "shot" back to 3.2.0 from 3.3.1 and got my batch endpoint back.
